[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/assets/*.png"
  [headers.values]
    Content-Type = "image/png"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
